/**
 * Workout PDF Generator
 * Features: Bilingual support (Ar/En), Custom Font loading for Arabic, Professional Design
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// CONFIG
const COLORS = {
    primary: '#f97316',      // Orange-500
    primaryDark: '#ea580c',  // Orange-600
    black: '#000000',
    darkBg: '#09090B',
    zinc900: '#18181B',
    zinc800: '#27272A',
    zinc700: '#3F3F46',
    zinc500: '#71717A',
    zinc300: '#D4D4D8',
    white: '#FFFFFF',
};

const TRANSLATIONS = {
    en: {
        workoutSchedule: 'WORKOUT SCHEDULE',
        client: 'Client',
        trainer: 'Trainer',
        date: 'Date',
        session: 'Session',
        exercise: 'Exercise',
        sets: 'Sets',
        reps: 'Reps',
        weight: 'Weight',
        technique: 'Technique',
        equipment: 'Equipment',
        notes: 'Notes',
        generatedBy: 'Generated by TFG',
        kg: 'kg',
        sessionNumber: 'Session #',
        totalExercises: 'Total Exercises',
        set: 'Set',
    },
    ar: {
        workoutSchedule: 'جدول التمارين',
        client: 'العميل',
        trainer: 'المدرب',
        date: 'التاريخ',
        session: 'الجلسة',
        exercise: 'التمرين',
        sets: 'المجموعات',
        reps: 'التكرارات',
        weight: 'الوزن',
        technique: 'الأسلوب',
        equipment: 'المعدات',
        notes: 'ملاحظات',
        generatedBy: 'تم الإنشاء بواسطة TFG',
        kg: 'كجم',
        sessionNumber: 'جلسة رقم',
        totalExercises: 'إجمالي التمارين',
        set: 'مجموعة',
    }
};

/**
 * Loads the Cairo font for Arabic support
 * Fetches from a reliable CDN to avoid massive base64 strings in code
 */
async function addArabicFont(pdf) {
    try {
        const fontUrl = 'https://cdn.jsdelivr.net/npm/@fontsource/cairo/files/cairo-arabic-700-normal.woff';
        const response = await fetch(fontUrl);
        const buffer = await response.arrayBuffer();
        const fontFileName = "Cairo-Bold.ttf";
        
        // Convert array buffer to base64 string
        let binary = '';
        const bytes = new Uint8Array(buffer);
        const len = bytes.byteLength;
        for (let i = 0; i < len; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        const base64Font = window.btoa(binary);

        pdf.addFileToVFS(fontFileName, base64Font);
        pdf.addFont(fontFileName, "Cairo", "bold");
        return true;
    } catch (error) {
        console.error("Failed to load Arabic font:", error);
        return false;
    }
}

export async function generateWorkoutPDF({
    sessionName = 'Workout Session',
    sessionNum = 1,
    exercises = [],
    clientName = 'Client Name',
    trainerName = 'Trainer Name',
    date = new Date().toLocaleDateString(),
    language = 'en'
}) {
    const t = TRANSLATIONS[language];
    const isRTL = language === 'ar';

    const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    // Load Arabic font if needed
    if (isRTL) {
        await addArabicFont(pdf);
        pdf.setFont("Cairo", "bold");
    } else {
        pdf.setFont("helvetica", "bold");
    }

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;

    // --- HEADER ---
    pdf.setFillColor(COLORS.darkBg);
    pdf.rect(0, 0, pageWidth, 60, 'F');
    pdf.setFillColor(COLORS.primary);
    pdf.rect(0, 0, pageWidth, 2, 'F');

    // Branding
    pdf.setFontSize(18);
    pdf.setTextColor(COLORS.white);
    pdf.text('TFG', margin, 17);

    // Title & Session Name
    const titleX = isRTL ? pageWidth - margin : margin;
    const titleAlign = isRTL ? 'right' : 'left';

    pdf.setFontSize(24);
    pdf.text(t.workoutSchedule, titleX, 35, { align: titleAlign });

    pdf.setFontSize(14);
    pdf.setTextColor(COLORS.primary);
    pdf.text(sessionName, titleX, 43, { align: titleAlign });

    // Session Badge
    const badgeX = isRTL ? margin : pageWidth - margin - 35;
    pdf.setFillColor(COLORS.primary);
    pdf.roundedRect(badgeX, 10, 35, 12, 3, 3, 'F');
    pdf.setFontSize(10);
    pdf.setTextColor(COLORS.black);
    pdf.text(`# ${sessionNum}`, badgeX + 17.5, 17.5, { align: 'center' });

    // --- INFO CARDS ---
    let yPos = 75;
    const cardWidth = (pageWidth - (margin * 2) - 10) / 3;
    const cardHeight = 22;

    const infoCards = [
        { label: t.client, value: clientName, icon: '👤' },
        { label: t.trainer, value: trainerName, icon: '💪' },
        { label: t.date, value: date, icon: '📅' }
    ];

    // Reverse cards for RTL layout to match reading direction
    const displayCards = isRTL ? [...infoCards].reverse() : infoCards;

    displayCards.forEach((card, index) => {
        const cardX = margin + (cardWidth + 5) * index;
        pdf.setFillColor(COLORS.zinc900);
        pdf.roundedRect(cardX, yPos, cardWidth, cardHeight, 3, 3, 'F');
        pdf.setFillColor(COLORS.primary);
        pdf.rect(cardX, yPos, cardWidth, 1, 'F');

        // Text positioning
        const textX = isRTL ? cardX + cardWidth - 5 : cardX + 5;
        const align = isRTL ? 'right' : 'left';

        pdf.setFontSize(8);
        pdf.setTextColor(COLORS.zinc500);
        pdf.text(card.label, textX, yPos + 8, { align: align });

        pdf.setFontSize(10);
        pdf.setTextColor(COLORS.white);
        // Clean text (remove icon for PDF rendering safety if font lacks emojis)
        pdf.text(card.value, textX, yPos + 16, { align: align });
    });

    yPos += 35;

    // --- EXERCISES ---
    exercises.forEach((exercise, i) => {
        if (yPos > pageHeight - 50) {
            pdf.addPage();
            yPos = 20;
        }

        // Header Bar
        pdf.setFillColor(COLORS.zinc900);
        pdf.roundedRect(margin, yPos, pageWidth - (margin * 2), 12, 2, 2, 'F');
        
        // Number Bubble
        const bubbleX = isRTL ? pageWidth - margin - 10 : margin + 5;
        pdf.setFillColor(COLORS.primary);
        pdf.circle(bubbleX + 2, yPos + 6, 4, 'F');
        pdf.setTextColor(COLORS.black);
        pdf.setFontSize(9);
        pdf.text(String(i + 1), bubbleX + 2, yPos + 7.5, { align: 'center' });

        // Exercise Name
        pdf.setTextColor(COLORS.white);
        pdf.setFontSize(12);
        const nameX = isRTL ? pageWidth - margin - 20 : margin + 15;
        const nameAlign = isRTL ? 'right' : 'left';
        pdf.text(exercise.name || `${t.exercise} ${i + 1}`, nameX, yPos + 8, { align: nameAlign });

        yPos += 15;

        // Table
        if (exercise.sets && exercise.sets.length > 0) {
            const tableBody = exercise.sets.map((set, idx) => [
                idx + 1,
                set.reps || '-',
                set.weight ? `${set.weight} ${t.kg}` : '-',
                set.technique || 'Regular',
                set.equipment || '-'
            ]);

            // For RTL tables, we might want to reverse columns, but standard numbers usually read LTR.
            // Keeping standard column order for data clarity.
            
            autoTable(pdf, {
                startY: yPos,
                head: [[t.set, t.reps, t.weight, t.technique, t.equipment]],
                body: tableBody,
                theme: 'grid',
                styles: {
                    fillColor: COLORS.darkBg,
                    textColor: COLORS.zinc300,
                    lineColor: COLORS.zinc800,
                    lineWidth: 0.1,
                    font: isRTL ? "Cairo" : "helvetica",
                    halign: 'center' // Center all data
                },
                headStyles: {
                    fillColor: COLORS.zinc800,
                    textColor: COLORS.primary,
                    fontStyle: 'bold'
                },
                margin: { left: margin, right: margin }
            });

            yPos = pdf.lastAutoTable.finalY + 10;
        }
    });

    const fileName = `${sessionName.replace(/\s/g, '_')}_${date.replace(/\//g, '-')}.pdf`;
    pdf.save(fileName);
}

export default generateWorkoutPDF;