# Generated by Django 6.0.1 on 2026-03-07 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manual_id", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="client_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nature_of_work",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        default="Active",
                        help_text="Active, Inactive, Injured, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "smoking",
                    models.BooleanField(
                        default=False, help_text="Is the client a smoker?"
                    ),
                ),
                (
                    "sleep_hours",
                    models.FloatField(
                        blank=True, help_text="Average hours of sleep", null=True
                    ),
                ),
                (
                    "is_child",
                    models.BooleanField(
                        default=False,
                        help_text="Distinguish between adult clients and children",
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(blank=True, default="Egypt", max_length=50),
                ),
                ("trained_gym_before", models.BooleanField(default=False)),
                ("trained_coach_before", models.BooleanField(default=False)),
                (
                    "injuries",
                    models.TextField(
                        blank=True, help_text="Injuries or Surgeries history", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=5, unique=True)),
                ("dial_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(help_text="Day number (1-7 or 1-14...)")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("snack_1", "Snack 1"),
                            ("lunch", "Lunch"),
                            ("snack_2", "Snack 2"),
                            ("dinner", "Dinner"),
                            ("snack_3", "Snack 3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_name",
                    models.CharField(
                        blank=True, help_text="Optional name", max_length=200, null=True
                    ),
                ),
                (
                    "meal_time",
                    models.TimeField(blank=True, help_text="Suggested time", null=True),
                ),
                ("total_calories", models.IntegerField(default=0)),
                ("total_protein", models.FloatField(default=0.0)),
                ("total_carbs", models.FloatField(default=0.0)),
                ("total_fats", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="meal_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["day", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("units", models.IntegerField(help_text="Number of sessions/visits")),
                (
                    "duration_days",
                    models.IntegerField(
                        help_text="Duration in days (e.g. 30 for 1 month)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "is_child_plan",
                    models.BooleanField(
                        default=False, help_text="Is this package for children?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingDaySplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(help_text="Day 1, Day 2, etc.")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sessions_used",
                    models.IntegerField(
                        default=0, help_text="Number of sessions attended"
                    ),
                ),
                ("inbody_height", models.FloatField(default=0.0)),
                ("inbody_weight", models.FloatField(default=0.0)),
                ("inbody_muscle", models.FloatField(default=0.0)),
                ("inbody_fat", models.FloatField(default=0.0)),
                ("inbody_tbw", models.FloatField(default=0.0)),
                (
                    "inbody_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weight Loss", "Weight Loss"),
                            ("Bulking", "Bulking"),
                            ("Cutting", "Cutting"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Weight Loss",
                        max_length=50,
                    ),
                ),
                (
                    "inbody_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Light", "Light"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        default="Moderate",
                        max_length=50,
                    ),
                ),
                ("inbody_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="clients.client",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "arabic_name",
                    models.CharField(
                        blank=True,
                        help_text="Name in Arabic",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("calories_per_100g", models.IntegerField()),
                ("protein_per_100g", models.FloatField()),
                ("carbs_per_100g", models.FloatField()),
                ("fats_per_100g", models.FloatField()),
                ("fiber_per_100g", models.FloatField(default=0.0)),
                (
                    "serving_unit",
                    models.CharField(
                        default="g",
                        help_text="e.g. 'slice', 'egg', 'scoop'",
                        max_length=50,
                    ),
                ),
                (
                    "grams_per_serving",
                    models.FloatField(
                        default=100.0, help_text="Weight of one serving in grams"
                    ),
                ),
                (
                    "common_serving_size",
                    models.FloatField(default=100, help_text="Common serving in grams"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified nutritional data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Food Database",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("day_name", models.CharField(max_length=20)),
                ("exercises_summary", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupSessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("deducted", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="clients.groupsessionlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupWorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("exercises", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualNutritionSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Internal ID, not printed",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("plan_name", models.CharField(default="My Plan", max_length=200)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_nutrition_saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ManualWorkoutSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Internal ID, not printed",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("session_name", models.CharField(default="Workout", max_length=200)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_workout_saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.FloatField(
                        default=0.0, help_text="Amount in grams or pieces"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="g", help_text="e.g. 'g', 'slice', 'egg'", max_length=50
                    ),
                ),
                ("calories", models.IntegerField(default=0)),
                ("protein", models.FloatField(default=0.0)),
                ("carbs", models.FloatField(default=0.0)),
                ("fats", models.FloatField(default=0.0)),
                (
                    "order",
                    models.IntegerField(default=1, help_text="Order within the meal"),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="clients.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Nutrition Plan", max_length=200)),
                (
                    "duration_weeks",
                    models.IntegerField(
                        default=1, help_text="How many weeks is this plan for?"
                    ),
                ),
                ("calc_gender", models.CharField(default="male", max_length=10)),
                ("calc_age", models.IntegerField(default=25)),
                (
                    "calc_height",
                    models.FloatField(default=170.0, help_text="Height in cm"),
                ),
                (
                    "calc_weight",
                    models.FloatField(default=70.0, help_text="Weight in kg"),
                ),
                (
                    "calc_activity_level",
                    models.CharField(default="moderate", max_length=50),
                ),
                (
                    "calc_tdee",
                    models.IntegerField(default=2000, help_text="Calculated TDEE"),
                ),
                (
                    "calc_defer_cal",
                    models.IntegerField(
                        default=500, help_text="Calorie deficit/surplus"
                    ),
                ),
                (
                    "calc_fat_percent",
                    models.FloatField(default=25.0, help_text="Fat percentage target"),
                ),
                (
                    "calc_protein_multiplier",
                    models.FloatField(default=2.0, help_text="Protein multiplier"),
                ),
                (
                    "calc_protein_advance",
                    models.IntegerField(
                        default=0, help_text="Additional protein adjustment"
                    ),
                ),
                ("calc_meals", models.IntegerField(default=3)),
                ("calc_snacks", models.IntegerField(default=2)),
                (
                    "calc_carb_adjustment",
                    models.CharField(default="moderate", max_length=50),
                ),
                (
                    "pdf_brand_text",
                    models.CharField(
                        blank=True,
                        help_text="Custom branding text for PDF export",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("target_calories", models.IntegerField(default=2000)),
                ("target_protein", models.FloatField(default=150.0)),
                ("target_carbs", models.FloatField(default=200.0)),
                ("target_fats", models.FloatField(default=60.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mealplan",
            name="nutrition_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_plans",
                to="clients.nutritionplan",
            ),
        ),
        migrations.CreateModel(
            name="SessionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                ("completed", models.BooleanField(default=False)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="clients.sessionexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SessionTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sessions_count",
                    models.IntegerField(help_text="How many sessions to transfer"),
                ),
                (
                    "schedule_notes",
                    models.TextField(
                        help_text="Days and times (e.g., Mon 5PM, Wed 3PM)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_requests",
                        to="clients.clientsubscription",
                    ),
                ),
                (
                    "to_trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainerShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_start",
                    models.TimeField(
                        default="08:00", help_text="Start of working day (HH:MM)."
                    ),
                ),
                (
                    "shift_end",
                    models.TimeField(
                        default="20:00", help_text="End of working day (HH:MM)."
                    ),
                ),
                (
                    "slot_duration",
                    models.IntegerField(
                        default=60,
                        help_text="Duration of each time slot in minutes (e.g. 60 = 1 hour).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.OneToOneField(
                        help_text="The trainer this shift belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="clients.trainingdaysplit",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle_length",
                    models.IntegerField(
                        help_text="How many days in a split? (e.g. 3 for PPL)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plan",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingdaysplit",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="clients.trainingplan",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "session_number")},
            },
        ),
        migrations.AddField(
            model_name="sessionexercise",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="clients.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="clients.trainingexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CoachSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=15)),
                (
                    "session_time",
                    models.TimeField(
                        blank=True,
                        help_text="Scheduled time for this group session",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_days",
                        to="clients.client",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("coach", "client", "day")},
            },
        ),
        migrations.CreateModel(
            name="NutritionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("actual_calories", models.IntegerField(default=0)),
                ("actual_protein", models.FloatField(default=0.0)),
                ("actual_carbs", models.FloatField(default=0.0)),
                ("actual_fats", models.FloatField(default=0.0)),
                (
                    "actual_water",
                    models.FloatField(default=0.0, help_text="Water intake in liters"),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Body weight in kg", null=True
                    ),
                ),
                (
                    "body_fat",
                    models.FloatField(
                        blank=True, help_text="Body fat percentage", null=True
                    ),
                ),
                (
                    "meals_completed",
                    models.IntegerField(
                        default=0, help_text="Number of meals completed"
                    ),
                ),
                (
                    "compliance_percentage",
                    models.IntegerField(default=0, help_text="Overall compliance %"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True, help_text="How client felt today", max_length=50
                    ),
                ),
                (
                    "energy_level",
                    models.IntegerField(default=5, help_text="Energy level 1-10"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nutrition_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="clients.nutritionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("nutrition_plan", "date")},
            },
        ),
        migrations.CreateModel(
            name="TrainerSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        help_text="Day number: 1=Monday … 7=Sunday.",
                    ),
                ),
                (
                    "time_slot",
                    models.TimeField(help_text="Start time of the slot (HH:MM)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client booked into this slot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="clients.client",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        help_text="The trainer who owns this slot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_schedule_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "time_slot"],
                "unique_together": {("trainer", "day_of_week", "time_slot")},
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("date_completed", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="clients.clientsubscription",
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.trainingdaysplit",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "session_number")},
            },
        ),
    ]
