# Generated by Django 6.0.1 on 2026-01-30 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manual_id", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="client_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nature_of_work",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        default="Active",
                        help_text="Active, Inactive, Injured, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "smoking",
                    models.BooleanField(
                        default=False, help_text="Is the client a smoker?"
                    ),
                ),
                (
                    "sleep_hours",
                    models.FloatField(
                        blank=True, help_text="Average hours of sleep", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("snack1", "Morning Snack"),
                            ("lunch", "Lunch"),
                            ("snack2", "Afternoon Snack"),
                            ("dinner", "Dinner"),
                            ("snack3", "Evening Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_name",
                    models.CharField(
                        blank=True, help_text="e.g., Chicken Rice Bowl", max_length=200
                    ),
                ),
                (
                    "meal_time",
                    models.TimeField(
                        blank=True, help_text="Suggested meal time", null=True
                    ),
                ),
                ("total_calories", models.IntegerField(default=0)),
                ("total_protein", models.FloatField(default=0.0)),
                ("total_carbs", models.FloatField(default=0.0)),
                ("total_fats", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Did client complete this meal?"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="meal_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["day", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("units", models.IntegerField(help_text="Number of sessions/visits")),
                (
                    "duration_days",
                    models.IntegerField(
                        help_text="Duration in days (e.g. 30 for 1 month)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingDaySplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(help_text="Day 1, Day 2, etc.")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sessions_used",
                    models.IntegerField(
                        default=0, help_text="Number of sessions attended"
                    ),
                ),
                (
                    "inbody_height",
                    models.FloatField(default=0.0, help_text="Height in CM"),
                ),
                (
                    "inbody_weight",
                    models.FloatField(default=0.0, help_text="Weight in KG"),
                ),
                (
                    "inbody_muscle",
                    models.FloatField(default=0.0, help_text="Muscle Mass in KG"),
                ),
                (
                    "inbody_fat",
                    models.FloatField(default=0.0, help_text="Body Fat Percentage"),
                ),
                (
                    "inbody_tbw",
                    models.FloatField(default=0.0, help_text="Total Body Water"),
                ),
                (
                    "inbody_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weight Loss", "Weight Loss"),
                            ("Bulking", "Bulking"),
                            ("Cutting", "Cutting"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Weight Loss",
                        max_length=50,
                    ),
                ),
                (
                    "inbody_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Light", "Light"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        default="Moderate",
                        max_length=50,
                    ),
                ),
                ("inbody_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="clients.client",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("calories_per_100g", models.IntegerField()),
                ("protein_per_100g", models.FloatField()),
                ("carbs_per_100g", models.FloatField()),
                ("fats_per_100g", models.FloatField()),
                ("fiber_per_100g", models.FloatField(default=0.0)),
                (
                    "common_serving_size",
                    models.FloatField(default=100, help_text="Common serving in grams"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified nutritional data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Food Database",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., Chicken Breast", max_length=200),
                ),
                (
                    "quantity",
                    models.FloatField(default=100, help_text="Quantity in grams or ml"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("piece", "Piece"),
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                ("calories", models.IntegerField(default=0)),
                ("protein", models.FloatField(default=0.0)),
                ("carbs", models.FloatField(default=0.0)),
                ("fats", models.FloatField(default=0.0)),
                ("fiber", models.FloatField(blank=True, default=0.0)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Protein", "Protein"),
                            ("Carbs", "Carbohydrates"),
                            ("Vegetables", "Vegetables"),
                            ("Fruits", "Fruits"),
                            ("Dairy", "Dairy"),
                            ("Fats", "Fats & Oils"),
                            ("Snacks", "Snacks"),
                            ("Beverages", "Beverages"),
                            ("Supplements", "Supplements"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "preparation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Grilled, Boiled, Raw",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="clients.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="New Diet Plan",
                        help_text="e.g. Winter Bulk",
                        max_length=100,
                    ),
                ),
                ("duration_weeks", models.IntegerField(default=4)),
                (
                    "calc_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "calc_age",
                    models.IntegerField(
                        blank=True,
                        help_text="Age in years (can be from client)",
                        null=True,
                    ),
                ),
                (
                    "calc_height",
                    models.FloatField(default=170.0, help_text="Height in cm"),
                ),
                ("calc_weight", models.FloatField(default=80.0)),
                (
                    "calc_activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("active", "Active"),
                            ("very_active", "Very Active"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("calc_tdee", models.IntegerField(default=2500)),
                ("calc_defer_cal", models.IntegerField(default=500)),
                ("calc_fat_percent", models.FloatField(default=25.0)),
                ("calc_protein_multiplier", models.FloatField(default=2.2)),
                ("calc_protein_advance", models.FloatField(default=0.8)),
                ("calc_meals", models.IntegerField(default=4)),
                ("calc_snacks", models.IntegerField(default=2)),
                ("target_calories", models.IntegerField(default=2000)),
                ("target_protein", models.IntegerField(default=150)),
                ("target_carbs", models.IntegerField(default=200)),
                ("target_fats", models.IntegerField(default=60)),
                ("water_intake", models.FloatField(default=3.0)),
                ("meals_per_day", models.IntegerField(default=5)),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("Balanced", "Balanced"),
                            ("High Protein", "High Protein"),
                            ("Low Carb", "Low Carb"),
                            ("Keto", "Keto"),
                            ("Vegan", "Vegan"),
                            ("Mediterranean", "Mediterranean"),
                        ],
                        default="Balanced",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mealplan",
            name="nutrition_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_plans",
                to="clients.nutritionplan",
            ),
        ),
        migrations.CreateModel(
            name="SessionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="clients.sessionexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="clients.trainingdaysplit",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle_length",
                    models.IntegerField(
                        help_text="How many days in a split? (e.g. 3 for PPL)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plan",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trainingdaysplit",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="clients.trainingplan",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "session_number")},
            },
        ),
        migrations.AddField(
            model_name="sessionexercise",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="clients.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="clients.trainingexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together={("nutrition_plan", "day", "meal_type")},
        ),
        migrations.CreateModel(
            name="NutritionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("actual_calories", models.IntegerField(default=0)),
                ("actual_protein", models.FloatField(default=0.0)),
                ("actual_carbs", models.FloatField(default=0.0)),
                ("actual_fats", models.FloatField(default=0.0)),
                (
                    "actual_water",
                    models.FloatField(default=0.0, help_text="Water intake in liters"),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Body weight in kg", null=True
                    ),
                ),
                (
                    "body_fat",
                    models.FloatField(
                        blank=True, help_text="Body fat percentage", null=True
                    ),
                ),
                (
                    "meals_completed",
                    models.IntegerField(
                        default=0, help_text="Number of meals completed"
                    ),
                ),
                (
                    "compliance_percentage",
                    models.IntegerField(default=0, help_text="Overall compliance %"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True, help_text="How client felt today", max_length=50
                    ),
                ),
                (
                    "energy_level",
                    models.IntegerField(default=5, help_text="Energy level 1-10"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nutrition_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="clients.nutritionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("nutrition_plan", "date")},
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("date_completed", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="clients.clientsubscription",
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.trainingdaysplit",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "session_number")},
            },
        ),
    ]
