# Generated by Django 6.0.1 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Coach notes, supplement recommendations, grocery list, etc.",
            ),
        ),
    ]
