# Generated by Django 6.0.1 on 2026-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nature_of_work",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sleep_hours",
            field=models.FloatField(
                blank=True, help_text="Average hours of sleep", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="smoking",
            field=models.BooleanField(
                default=False, help_text="Is the client a smoker?"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                default="Active",
                help_text="Active, Inactive, Injured, etc.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="manual_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
