# Generated by Django 6.0.1 on 2026-02-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritionplan",
            name="pdf_brand_text",
            field=models.CharField(
                default="TFG", help_text="Text to display as logo on PDF", max_length=50
            ),
        ),
    ]
