# Generated by Django 6.0.1 on 2026-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooddatabase",
            name="grams_per_serving",
            field=models.FloatField(
                default=100.0, help_text="Weight of one serving in grams"
            ),
        ),
        migrations.AddField(
            model_name="fooddatabase",
            name="serving_unit",
            field=models.CharField(
                default="g", help_text="e.g. 'slice', 'egg', 'scoop'", max_length=50
            ),
        ),
    ]
