# Generated by Django 6.0.1 on 2026-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_fooddatabase_grams_per_serving_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_carb_adjustment",
            field=models.IntegerField(default=0, help_text="Percentage +/- for carbs"),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="pdf_brand_text",
            field=models.CharField(
                default="AZ", help_text="Text to display as logo on PDF", max_length=50
            ),
        ),
    ]
