# Generated by Django 6.0.1 on 2026-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_sessiontransferrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooddatabase",
            name="arabic_name",
            field=models.CharField(
                blank=True, help_text="Name in Arabic", max_length=200, null=True
            ),
        ),
    ]
