# Generated by Django 6.0.1 on 2026-02-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_nutritionplan_pdf_brand_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionexercise",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
