# Generated by Django 6.0.1 on 2026-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_sessionexercise_note"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="fiber",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="preparation",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="nutritionplan",
            name="diet_type",
        ),
        migrations.RemoveField(
            model_name="nutritionplan",
            name="meals_per_day",
        ),
        migrations.RemoveField(
            model_name="nutritionplan",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="nutritionplan",
            name="water_intake",
        ),
        migrations.AddField(
            model_name="coachschedule",
            name="session_time",
            field=models.TimeField(
                blank=True, help_text="Scheduled time for this group session", null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="amount",
            field=models.FloatField(default=0.0, help_text="Amount in grams or pieces"),
        ),
        migrations.AddField(
            model_name="sessionset",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="order",
            field=models.IntegerField(default=1, help_text="Order within the meal"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="unit",
            field=models.CharField(
                default="g", help_text="e.g. 'g', 'slice', 'egg'", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="day",
            field=models.IntegerField(help_text="Day number (1-7 or 1-14...)"),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="meal_name",
            field=models.CharField(
                blank=True, help_text="Optional name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="meal_time",
            field=models.TimeField(blank=True, help_text="Suggested time", null=True),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("snack_1", "Snack 1"),
                    ("lunch", "Lunch"),
                    ("snack_2", "Snack 2"),
                    ("dinner", "Dinner"),
                    ("snack_3", "Snack 3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_activity_level",
            field=models.CharField(default="moderate", max_length=50),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_age",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_carb_adjustment",
            field=models.CharField(default="moderate", max_length=50),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_defer_cal",
            field=models.IntegerField(default=500, help_text="Calorie deficit/surplus"),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_fat_percent",
            field=models.FloatField(default=25.0, help_text="Fat percentage target"),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_gender",
            field=models.CharField(default="male", max_length=10),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_meals",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_protein_advance",
            field=models.IntegerField(
                default=0, help_text="Additional protein adjustment"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_protein_multiplier",
            field=models.FloatField(default=2.0, help_text="Protein multiplier"),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_tdee",
            field=models.IntegerField(default=2000, help_text="Calculated TDEE"),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_weight",
            field=models.FloatField(default=70.0, help_text="Weight in kg"),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="duration_weeks",
            field=models.IntegerField(
                default=1, help_text="How many weeks is this plan for?"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="name",
            field=models.CharField(default="Nutrition Plan", max_length=200),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="pdf_brand_text",
            field=models.CharField(
                blank=True,
                help_text="Custom branding text for PDF export",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_carbs",
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_fats",
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_protein",
            field=models.FloatField(default=150.0),
        ),
        migrations.AlterField(
            model_name="sessionexercise",
            name="note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="trainingexercise",
            name="note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
