# Generated by Django 6.0.1 on 2026-01-27 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "inbody_weight",
                    models.FloatField(default=0.0, help_text="Weight in KG"),
                ),
                (
                    "inbody_muscle",
                    models.FloatField(default=0.0, help_text="Muscle Mass in KG"),
                ),
                (
                    "inbody_fat",
                    models.FloatField(default=0.0, help_text="Body Fat Percentage"),
                ),
                ("inbody_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="clients.client",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.subscription",
                    ),
                ),
            ],
        ),
    ]
