# Generated by Django 6.0.1 on 2026-02-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_nutritionplan_calc_carb_adjustment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_child",
            field=models.BooleanField(
                default=False,
                help_text="Distinguish between adult clients and children",
            ),
        ),
    ]
