# Generated by Django 6.0.1 on 2026-01-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
