# Generated by Django 6.0.1 on 2026-02-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_is_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_child_plan",
            field=models.BooleanField(
                default=False, help_text="Is this package for children?"
            ),
        ),
    ]
