# Generated by Django 6.0.1 on 2026-02-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_subscription_is_child_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, default="Egypt", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="injuries",
            field=models.TextField(
                blank=True, help_text="Injuries or Surgeries history", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="trained_coach_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="trained_gym_before",
            field=models.BooleanField(default=False),
        ),
    ]
