# Generated by Django 6.0.1 on 2026-01-27 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_clientsubscription_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsubscription",
            name="inbody_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Light", "Light"),
                    ("Moderate", "Moderate"),
                    ("High", "High"),
                ],
                default="Moderate",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="inbody_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Weight Loss", "Weight Loss"),
                    ("Bulking", "Bulking"),
                    ("Cutting", "Cutting"),
                    ("Maintenance", "Maintenance"),
                ],
                default="Weight Loss",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="inbody_height",
            field=models.FloatField(default=0.0, help_text="Height in CM"),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="inbody_tbw",
            field=models.FloatField(default=0.0, help_text="Total Body Water"),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="sessions_used",
            field=models.IntegerField(
                default=0, help_text="Number of sessions attended"
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
