# Generated by Django 6.0.1 on 2026-01-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_clientsubscription_inbody_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle_length",
                    models.IntegerField(
                        help_text="How many days in a split? (e.g. 3 for PPL)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plan",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingDaySplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(help_text="Day 1, Day 2, etc.")),
                ("name", models.CharField(max_length=100)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="clients.trainingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
