# Generated by Django 6.0.1 on 2026-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_country_client_injuries_client_parent_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=5, unique=True)),
                ("dial_code", models.CharField(max_length=10)),
                ("flag", models.CharField(max_length=10)),
            ],
        ),
    ]
