# Generated by Django 6.0.1 on 2026-01-27 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_trainingplan_trainingdaysplit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("sets", models.CharField(blank=True, max_length=50)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="clients.trainingdaysplit",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
