# Generated by Django 6.0.1 on 2026-02-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="flag",
        ),
    ]
