# Generated by Django 6.0.1 on 2026-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_remove_country_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="inbody_fat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="inbody_height",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="inbody_muscle",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="inbody_tbw",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="inbody_weight",
            field=models.FloatField(default=0.0),
        ),
    ]
