# Generated by Django 6.0.1 on 2026-01-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_remove_trainingexercise_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SessionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("reps", models.CharField(blank=True, max_length=50)),
                ("weight", models.CharField(blank=True, max_length=50)),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Drop Set", "Drop Set"),
                            ("Super Set", "Super Set"),
                            ("Pyramid", "Pyramid"),
                            ("Negative", "Negative"),
                        ],
                        default="Regular",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bodyweight", "Bodyweight"),
                            ("Dumbbell", "Dumbbell"),
                            ("Barbell", "Barbell"),
                            ("Cable", "Cable"),
                            ("Machine", "Machine"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="clients.sessionexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("subscription", "session_number")},
            },
        ),
        migrations.AddField(
            model_name="sessionexercise",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="clients.trainingsession",
            ),
        ),
    ]
