# Generated by Django 6.0.1 on 2026-01-28 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_trainingsession_completed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("snack1", "Morning Snack"),
                            ("lunch", "Lunch"),
                            ("snack2", "Afternoon Snack"),
                            ("dinner", "Dinner"),
                            ("snack3", "Evening Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_name",
                    models.CharField(
                        blank=True, help_text="e.g., Chicken Rice Bowl", max_length=200
                    ),
                ),
                (
                    "meal_time",
                    models.TimeField(
                        blank=True, help_text="Suggested meal time", null=True
                    ),
                ),
                ("total_calories", models.IntegerField(default=0)),
                ("total_protein", models.FloatField(default=0.0)),
                ("total_carbs", models.FloatField(default=0.0)),
                ("total_fats", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Did client complete this meal?"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="meal_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["day", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="FoodDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("calories_per_100g", models.IntegerField()),
                ("protein_per_100g", models.FloatField()),
                ("carbs_per_100g", models.FloatField()),
                ("fats_per_100g", models.FloatField()),
                ("fiber_per_100g", models.FloatField(default=0.0)),
                (
                    "common_serving_size",
                    models.FloatField(default=100, help_text="Common serving in grams"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified nutritional data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Food Database",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., Chicken Breast", max_length=200),
                ),
                (
                    "quantity",
                    models.FloatField(default=100, help_text="Quantity in grams or ml"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("piece", "Piece"),
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                ("calories", models.IntegerField(default=0)),
                ("protein", models.FloatField(default=0.0)),
                ("carbs", models.FloatField(default=0.0)),
                ("fats", models.FloatField(default=0.0)),
                ("fiber", models.FloatField(blank=True, default=0.0)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Protein", "Protein"),
                            ("Carbs", "Carbohydrates"),
                            ("Vegetables", "Vegetables"),
                            ("Fruits", "Fruits"),
                            ("Dairy", "Dairy"),
                            ("Fats", "Fats & Oils"),
                            ("Snacks", "Snacks"),
                            ("Beverages", "Beverages"),
                            ("Supplements", "Supplements"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "preparation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Grilled, Boiled, Raw",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="clients.mealplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_calories",
                    models.IntegerField(default=2000, help_text="Daily calorie target"),
                ),
                (
                    "target_protein",
                    models.IntegerField(
                        default=150, help_text="Daily protein in grams"
                    ),
                ),
                (
                    "target_carbs",
                    models.IntegerField(default=200, help_text="Daily carbs in grams"),
                ),
                (
                    "target_fats",
                    models.IntegerField(default=60, help_text="Daily fats in grams"),
                ),
                (
                    "water_intake",
                    models.FloatField(
                        default=3.0, help_text="Daily water intake in liters"
                    ),
                ),
                (
                    "meals_per_day",
                    models.IntegerField(default=5, help_text="Number of meals per day"),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("Balanced", "Balanced"),
                            ("High Protein", "High Protein"),
                            ("Low Carb", "Low Carb"),
                            ("Keto", "Keto"),
                            ("Vegan", "Vegan"),
                            ("Mediterranean", "Mediterranean"),
                        ],
                        default="Balanced",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about the nutrition plan"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plan",
                        to="clients.clientsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mealplan",
            name="nutrition_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_plans",
                to="clients.nutritionplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealplan",
            unique_together={("nutrition_plan", "day", "meal_type")},
        ),
        migrations.CreateModel(
            name="NutritionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("actual_calories", models.IntegerField(default=0)),
                ("actual_protein", models.FloatField(default=0.0)),
                ("actual_carbs", models.FloatField(default=0.0)),
                ("actual_fats", models.FloatField(default=0.0)),
                (
                    "actual_water",
                    models.FloatField(default=0.0, help_text="Water intake in liters"),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Body weight in kg", null=True
                    ),
                ),
                (
                    "body_fat",
                    models.FloatField(
                        blank=True, help_text="Body fat percentage", null=True
                    ),
                ),
                (
                    "meals_completed",
                    models.IntegerField(
                        default=0, help_text="Number of meals completed"
                    ),
                ),
                (
                    "compliance_percentage",
                    models.IntegerField(default=0, help_text="Overall compliance %"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True, help_text="How client felt today", max_length=50
                    ),
                ),
                (
                    "energy_level",
                    models.IntegerField(default=5, help_text="Energy level 1-10"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nutrition_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="clients.nutritionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("nutrition_plan", "date")},
            },
        ),
    ]
