# Generated by Django 6.0.1 on 2026-01-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0012_mealplan_fooddatabase_fooditem_nutritionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_activity_factor",
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_fat_percent",
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_protein_ratio",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_weight",
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="duration_weeks",
            field=models.IntegerField(
                default=4, help_text="Duration of this diet phase"
            ),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="name",
            field=models.CharField(
                default="New Diet Plan",
                help_text="e.g. Bulking Phase 1",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="meals_per_day",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_plans",
                to="clients.clientsubscription",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_calories",
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_carbs",
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_fats",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="target_protein",
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="water_intake",
            field=models.FloatField(default=3.0),
        ),
    ]
