# Generated by Django 6.0.1 on 2026-01-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_nutritionplan_calc_activity_factor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionplan",
            name="calc_activity_factor",
        ),
        migrations.RemoveField(
            model_name="nutritionplan",
            name="calc_protein_ratio",
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_defer_cal",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_meals",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_protein_advance",
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_protein_multiplier",
            field=models.FloatField(default=2.2),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_snacks",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="calc_tdee",
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="calc_fat_percent",
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="duration_weeks",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="name",
            field=models.CharField(
                default="New Diet Plan", help_text="e.g. Winter Bulk", max_length=100
            ),
        ),
    ]
